/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_structgen_StructGenJNI */

#ifndef _Included_org_structgen_StructGenJNI
#define _Included_org_structgen_StructGenJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_structgen_StructGenJNI
 * Method:    getcanmultig
 * Signature: (I[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_structgen_StructGenJNI_getcanmultig
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     org_structgen_StructGenJNI
 * Method:    getcanmultig2
 * Signature: (II[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_structgen_StructGenJNI_getcanmultig2
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
