/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_omg_OMGJNI */

#ifndef _Included_org_omg_OMGJNI
#define _Included_org_omg_OMGJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_omg_OMGJNI
 * Method:    getcanmultig
 * Signature: (I[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_omg_OMGJNI_getcanmultig
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray);

/*
 * Class:     org_omg_OMGJNI
 * Method:    getcanmultig2
 * Signature: (II[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_omg_OMGJNI_getcanmultig2
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
